version: '3.8'
services:
  web:
    build:
      context: AERApi/
    ports:
      - "8091:8000"
    volumes:
      - ./:/app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    links:
      - db:postgresql
    depends_on:
      - db
    networks:
      - AER
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    container_name: postgres_db
    networks:
      - AER
  pgadmin:
    build: ./pgadmin
    container_name: pgadmin4_AER
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: christianyepesgomez@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8090:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - AER
  spiders:
    build: ./AERData
    links:
      - db:posgresql
    networks:
      - AER

networks:
  AER:
    driver: bridge