# Generated by Django 3.2.11 on 2022-05-08 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id_problem', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('no_repeated_accepteds', models.IntegerField()),
                ('wrong_answer', models.IntegerField()),
                ('accepteds', models.IntegerField()),
                ('shipments', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('presentation_error', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('other', models.IntegerField()),
                ('restricted_function', models.IntegerField()),
                ('compilation_error', models.IntegerField()),
                ('c_shipments', models.IntegerField()),
                ('cpp_shipments', models.IntegerField()),
                ('java_shipments', models.IntegerField()),
            ],
            options={
                'db_table': 'problems',
            },
        ),
        migrations.CreateModel(
            name='ProblemsCategories',
            fields=[
                ('id_problem', models.OneToOneField(db_column='id_problem', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='problemas.problems')),
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categories')),
            ],
            options={
                'db_table': 'problems_categories',
                'unique_together': {('id_problem', 'id_category')},
            },
        ),
    ]
