# Generated by Django 3.2.11 on 2022-05-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistUsers',
            fields=[
                ('id_blacklist', models.AutoField(primary_key=True, serialize=False)),
                ('number_user', models.IntegerField()),
            ],
            options={
                'db_table': 'blacklist_users',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=100)),
                ('logo_src', models.CharField(blank=True, max_length=255, null=True)),
                ('shipments', models.IntegerField()),
                ('total_accepteds', models.IntegerField()),
                ('intents', models.IntegerField()),
                ('accepteds', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
