# Generated by Django 3.2.11 on 2022-05-08 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('related_category', models.ForeignKey(blank=True, db_column='related_category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categories')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
